
import type { Metadata } from "next";
import {
  // Poppins,

  Averia_Sans_Libre
} from "next/font/google";
import "./globals.css";
import Footer from "@/components/Helper/Footer";
import NavBarResponsive from "@/components/Helper/NavBarResponsive";
import LoadingProvider from "@/components/Helper/LoadingProvider";


// const poppins = Poppins({
//   subsets: ["latin"],
//   weight: ["300", "400", "700", "800"], // Add the required font weights 
//   style: ["normal", "italic"], // Optional styles
//   variable: "--font-poppins",
// });

const averia = Averia_Sans_Libre({
  subsets: ["latin"],
  weight: ["400", "700"], // Specify weights as needed
});



export const metadata: Metadata = {


    icons: "../favicon.ico",

  title: "Insure Cow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${averia.className
          } antialiased`}
      >


        <NavBarResponsive />
        <LoadingProvider>{children}</LoadingProvider>
        <Footer />
      </body>
    </html>
  );
}
